# Generated by Django 3.2 on 2023-06-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_candidate_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='contact',
            field=models.IntegerField(default=0),
        ),
    ]
