# Generated by Django 3.2 on 2023-06-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_candidate_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='tech_skills',
            field=models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('Ruby', 'Ruby'), ('Docker', 'Docker'), ('Node', 'Node'), ('JS', 'JS')], max_length=10),
        ),
    ]
